services:
  - type: web
    name: your-app-name
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false 



     


# mac@Macs-MacBook-Pro depth_and_core-main % git initgit add README.md
# git commit -m "first commit"
# git branch -M main     
# git remote add origin https://github.com/Kartik7974/depth_and_core.git
# git push -u origin main