databases:
  - name: depth_and_core
    databaseName: depth_and_core
    user: depth_and_core_user
    plan: free

services:
  - type: web
    name: depth_and_core-2
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: depth_and_core
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production



     


# mac@Macs-MacBook-Pro depth_and_core-main % git initgit add README.md
# git commit -m "first commit"
# git branch -M main     
# git remote add origin https://github.com/Kartik7974/depth_and_core.git
# git push -u origin main