databases:
  - name: depth_and_core_db
    databaseName: depth_and_core_production
    user: depth_and_core
    plan: free

services:
  - type: web
    name: depth_and_core
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: depth_and_core_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: NODE_VERSION
        value: 16.20.0
    plan: free



     


# mac@Macs-MacBook-Pro depth_and_core-main % git initgit add README.md
# git commit -m "first commit"
# git branch -M main     
# git remote add origin https://github.com/Kartik7974/depth_and_core.git
# git push -u origin main